First project microverse
alphym/hello_microverse_new pull request #1
Opened 2023-01-16 20:26 UTC by alphym

first project of microverse "hello microverse "

2023-01-16 22:18 UTC, AbayomiOlaoye requested changes
Hi @alphym  👋 , 

Good job with this milestone so far!
There are just few more issues to work on before moving onto the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Good implementation ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 22:18 UTC, AbayomiOlaoye commented on README.md
> +
- A descriptive README is an asset that has the capability of impressing recruiters, showcasing your documentation skills and share your thoughts pattern to users/visitors 👏 👏 .
- It's nice you used the required [README template](https://github.com/microverseinc/readme-template). How ever, I think you should consider making the following changes to customize the content:

- All main headers from the README template should be present in your repo (as they are).
  - The only **optional** section is FAQ.
  - It is important to add the section **Future Features**, and include 1-3 potential features of your project.
* Kindly **remove the section description**, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed and fill in your custom content.
- Another important editing is to remember to remove **template logo**. Optionally, you can replace it with your own logo if they have one.

2023-01-17 13:11 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @alphym , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 13:11 UTC, bobb-Rob commented on README.md
> +  </ul>
- [ ] You did well using the correct README template. However, you have not customized it to suit your project. 

- Remove the Microverse logo. If you have your logo, you can use it but I would advise you to remove it. 🙏
- For the Tech Stack Section, Kindly remove the Server and Database subsections because the technologies listed there are not relevant to this project. For the Client section, kindly include HTML and CSS 👍
- For the Key Features section, kindly highlight what this project is all about. This will make it easy for those who go through this repository to know what was implemented by reading the README.md file. 👍
- For the Prerequisite Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:

  - Installation of Git
  - Installation of NPM
  - A working browser
  - Internet connection
  - A code editor like Visual Studio Code
  - Installation of Live Server plugging in Visual Studio Code
  - Any other tool you can think about

- For the Setup section, kindly add instructions for cloning your repository on a local machine 👍
- For the Install section, kindly add instructions for setting up linters used in this project
- For the Usage section, include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.
- For the MIT section, kindly add a valid LICENSE. You can follow the instructions on the right side of the article attached below to set up a valid LICENSE. https://choosealicense.com/licenses/mit/

**Kindly implement all the changes listed above. It will make your README.md file look professional and it will give you an idea of how to set README.md files for most of the projects you will execute as a Microverse student.**

2023-01-17 16:02 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @alphym, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions
- So you can see that You want to make a list.
![image](https://user-images.githubusercontent.com/61361037/212943999-b8a152db-0932-4694-bcb0-f618d5c3f0d8.png)
The issue is `Single Space` between `-` and `ITEM`
For Example:
```
- ITEM01
- ITEM02
- ITEM03
``` 
This will enlist items like that
```
• ITEM01
• ITEM02
• ITEM03
````
- _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 16:02 UTC, RaoAkif commented on README.md
> +2.Right click on a HTML file from your visual studio and click on Open with Live Server
[OPTIONAL]
![](https://user-images.githubusercontent.com/61361037/212943999-b8a152db-0932-4694-bcb0-f618d5c3f0d8.png)
Use [this](https://www.markdownguide.org/basic-syntax/) guide to make a correction in generating a list.

2023-01-17 16:02 UTC, RaoAkif commented on README.md
> +
[OPTIONAL] Remove the comments/commands.
- This is not a Rails project
- Keep the files as much clean as you can. You can get this code back, from your previous commits.

2023-01-17 16:34 UTC, merged